#  workflow pipeline
name: sushiswap

on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
      
  pull_request:
    branches: [ master ]

  pull_request_target:
    branches:
    - master
    - develop

# ensure permissions are explicitly defined
# by configuring one we disable the remaining permissions
# see: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idpermissions
# permissions:
#  contents: read

# ensure multiple CI processes are not running analysis on contracts
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}
  FORCE_COLOR: 2


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ["14.x"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2
        with:
         ref: ${{github.event.pull_request.head.ref}}
         repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Nodejs  ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          always-auth: true
          registry-url: https://registry.npmjs.org
          
      - name: Install and Compile
        run: |
          yarn install
          yarn build

      - name: Test and Coverage
        run: |
          yarn test

  mythx:
    runs-on: ubuntu-latest
    env:
      MYTHX_API_KEY: ${{ secrets.MYTHX }}

    steps:
      - name: Nodejs 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          check-latest: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install MythX CLI
        run: python -m pip install mythx-cli
      - name: Print version info
        run: |
          python3 -V
          mythx version

      - uses: actions/checkout@v2
        with:
         ref: ${{github.event.pull_request.head.ref}}
         repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Install dependencies
        run: yarn install

      - name: Submit contracts
        run: mythx analyze
